### ISSUE TITLE
Add TTGO T-Beam to wiki Boards and Pins page

### ISSUE THREAD

**Issue by jcwren** [manuelbl/ttn-esp32#12]
Would you mind adding the TTGO T-Beam info to the `Boards and Pins` page of the wiki?

GitHub page with image, etc: https://github.com/LilyGO/TTGO-T-Beam

It may be worth noting on the wiki that the NEO-6M that purports to be on the board is usually counterfeit, and is actually a Hangzhou ZhongKe Microelectronics AT6558 part (datasheet: AT6558 BDS/GNSS Full Constellation SOC Chip Data Sheet
www.icofchina.com/d/file/xiazai/2016.../b1be6f481cdf9d773b963ab30a2d11d8.pdf), so the ublox UBX mode isn't supported. 

Here's the pin list:

```
#define TTN_SPI_HOST      HSPI_HOST
#define TTN_SPI_DMA_CHAN  1
#define TTN_PIN_SPI_SCLK  5
#define TTN_PIN_SPI_MOSI  27
#define TTN_PIN_SPI_MISO  19
#define TTN_PIN_NSS       18
#define TTN_PIN_RXTX      TTN_NOT_CONNECTED
#define TTN_PIN_RST       23
#define TTN_PIN_DIO0      26
#define TTN_PIN_DIO1      33
```

It may be worthwhile noting the above pin list is for the V6 boards. Looking at the V7 board on the website, it appears that DIO1 and DIO2 may not be supported. I don't have a V7 board to test this on.

Uses standard 40MHz system clock. 

I use the ublox UBX mode in a couple products, and replaced the NEO-6M with a NEO-M8Q. I have some example code that pushes the GPS position and ESP-32 chip temperature to The Things Network. I'm fine with sharing it, but as it parses the UBX output and not NMEA, it won't be useful to anyone who doesn't replace the NEO-6M with an authentic ublox part.

**Comment by manuelbl** [comment]
It's a wiki. Unless I have misconfigured it, every GitHub user should have the right to change the page.

You are very welcome to add the TTGO T-Beam to the page.

**Comment by jcwren** [comment]
I don't see a way to edit it. It's quite possible I'm blindly missing it, but only option I see is to clone it locally, and GitHub doesn't support PRs for wikis.

**Comment by manuelbl** [comment]
Sorry, it was restricted indeed.

I've changed it and you should now find an *Edit* button in the top right corner.

**Comment by manuelbl** [comment]
I've finally added the board to the Wikil
