### ISSUE TITLE
SF9 for RX2 in Europe

### ISSUE THREAD

**Issue by manuelbl** [manuelbl/ttn-esp32#17]
Set RX2 to SF9 for joining. After the join, the network takes care of it.

**Comment by manuelbl** [comment]
Looks as if this is wrong: https://github.com/TheThingsNetwork/ttn/issues/155

SF12 is used during join. The rest is automatic. So there is probably no code change needed.

**Comment by cyberman54** [comment]
I read contradictory statements on this. What is right?

**Comment by manuelbl** [comment]
It's definitely SF12 before and for joining. The join response will then configure whatever is needed later. So no action needed.
