### ISSUE TITLE
event EV_JOIN_FAILED

### ISSUE THREAD

**Issue by microgenios** [manuelbl/ttn-esp32#22]
I (0) cpu_start: App cpu up.
I (197) heap_init: Initializing. RAM available for dynamic allocation:
I (204) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (210) heap_init: At 3FFB3228 len 0002CDD8 (179 KiB): DRAM
I (216) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (222) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (229) heap_init: At 4008ABB4 len 0001544C (85 KiB): IRAM
I (235) cpu_start: Pro cpu start user code
I (29) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (111) ttn_hal: IO initialized
I (111) ttn_hal: SPI initialized
I (111) ttn_hal: Timer initialized
I (131) ttn_prov: Dev and app EUI and app key saved in NVS storage
I (131) ttn_prov: Dev and app EUI and app key saved in NVS storage
Joining...
I (131) ttn: event EV_JOINING
I (141) ttn: event EV_TXSTART
I (7491) ttn: event EV_TXSTART
I (22241) ttn: event EV_TXSTART
I (29631) ttn: event EV_TXSTART
I (38821) ttn: event EV_TXSTART
I (45881) ttn: event EV_TXSTART
I (56601) ttn: event EV_TXSTART
I (63571) ttn: event EV_TXSTART
I (85311) ttn: event EV_TXSTART
I (92591) ttn: event EV_TXSTART
I (99701) ttn: event EV_TXSTART
I (106511) ttn: event EV_TXSTART
I (125831) ttn: event EV_TXSTART
I (132461) ttn: event EV_TXSTART
I (150531) ttn: event EV_TXSTART
I (157131) ttn: event EV_TXSTART
I (163221) ttn: event EV_JOIN_FAILED
I (173881) ttn: event EV_TXSTART
I (180911) ttn: event EV_TXSTART
I (196591) ttn: event EV_TXSTART
I (203091) ttn: event EV_TXSTART
I (216811) ttn: event EV_TXSTART
I (223821) ttn: event EV_TXSTART
I (239891) ttn: event EV_TXSTART
I (246541) ttn: event EV_TXSTART
I (254371) ttn: event EV_TXSTART
I (261211) ttn: event EV_TXSTART
I (274851) ttn: event EV_TXSTART
I (282221) ttn: event EV_TXSTART

**Comment by manuelbl** [comment]
And your issue is...?
