### ISSUE TITLE
Is it possible to have a full C version

### ISSUE THREAD

**Issue by netmonk** [manuelbl/ttn-esp32#38]
meddling C and C++ is quite annoying. 
Is it possible to have a full C version for esp-idf. 
As far as LMIC stands for LoraMac In C :)

**Comment by manuelbl** [comment]
I'll think about. 

LMIC is the current underlying implementation. But it might be exchanged for another one in the future.

**Comment by manuelbl** [comment]
The upcoming version will support a C interface: see https://github.com/manuelbl/ttn-esp32/blob/master/include/ttn.h.

I would appreciate if you could give C interface in the master branch a test.
