### ISSUE TITLE
Device Class B support

### ISSUE THREAD

**Issue by FloStar3000** [manuelbl/ttn-esp32#45]
Hello,

the documentation and/or code does not indicate whether this library supports the device class B.
It would be great for my application to achieve a lower downlink latency.

If not, I would try to implement the Class B support myself, as the arduino-lmic library, which this builds on, states it supports Class B.
Could then someone give me a clue on what needs to be changed?

Best Regards,
Florian

**Comment by manuelbl** [comment]
This library does not support class B devices / mode. I will add it to the documentation.

I'm not really familiar with class B operations. But from what I understand, the changes wouldn't be trivial.
