### ISSUE TITLE
Feature request: Keep session during deep sleep.

### ISSUE THREAD

**Issue by jpmeijers** [manuelbl/ttn-esp32#5]
When an ESP32 goes into deep sleep, the main memory is cleared. The programs starts from the beginning when the device wakes up.

Using ttn-esp32, at startup a join procedure is done. Say I have a device that only wakes up very seldomly. This device should only join once (in the factory/during initial programming), or periodically (±once a month). Therefore the state of the LoRaWAN session should be kept during sleep, and updated when a transmission is made.

Possible solution:
1. After a successful join save the session (AppSessionKey, NetworkSessionKey, UplinkFrameCounter, DownlinkFrameCounter) in RTC memory (or in Flash).
2. At startup check if there is a valid session stored in RTC memory. If there is a valid session, do not do the provisioning/joining and use the existing session.
3. If we do not have a session stored, do a join and save the session.
4. When sending a message, update the frame counters of this session.
5. When receiving a message, update the frame counters of this session.

Nr 4 and 5 should already be done by LMIC, but it is in volatile memory. If we can move the variables that are use by LMIC for the session keys and frame counters to non-volatile memory it will already solve most of this. Then we just need a way to query the current session to see if we need to join or not. LMIC already has a way to do this too - it only joins when the first message is sent, and never joins when a session is hardcoded (ABP mode).

**Comment by manuelbl** [comment]
This feature is already on my wish list. I recently stumbled upon this [LMIC modification](https://github.com/ngraziano/lmicesp32) that seems to have implemented this. It saves and restores all relevant LMIC data into RTC RAM.

**Comment by jpmeijers** [comment]
O wow, that looks great. Thanks for linking me to that library.

**Comment by Beliwars** [comment]
Hello @ngraziano did you correct the time overflow issue on your modified version of LMIC?

**Comment by ngraziano** [comment]
Hello @Beliwars 
For os_getTime I use the RTC to get the value but it may overflow the same way than other LMIC version because I also use an uint32, so the I never sleep more than 1 hour and I do not have problems. (overflow is every 9,5 hours if my maths are correct).

**Comment by manuelbl** [comment]
In order to go to deep sleep and still be a good network citizen, a lot of parameters have to be saved and restored.  Currently, the underlying MCCI LMIC library does not support it even though there are discussions about implementing it. The feature would be a huge win for many applications.

I will implement it in this library if the MCCI LMIC implements it or if I find another suitable library that could be used instead of MCCI LMIC.

For now, I'm going to close this issue.
