### ISSUE TITLE
Not possible to navigate menuconfig menu when using platformio

### ISSUE THREAD

**Issue by mike6000** [manuelbl/ttn-esp32#52]
Navigating menuconfig was not possible inside platformio. None of the keys (up, down arrow etc) worked. However ESC worked. 
![image](https://user-images.githubusercontent.com/18505778/168552133-252b68f3-7f1f-472b-8a02-4c6337a2fd3c.png)
By running pio run -t menuconfig instead in a cmd window outside platformio the navigation keys worked.
(Windows 10 OS)

**Comment by manuelbl** [comment]
This is a known incompatibility between Visual Studio Code and ESP-IDF. See e.g. https://github.com/espressif/vscode-esp-idf-extension/issues/6

Several workarounds are mentioned. But I'm not sure if they are all compatible with PlatformIO. Espressif recommends to use the ESP-IDF extension instead. But that's a non-PlatformIO as well.

**Comment by mike6000** [comment]
My workaround was to open a separate cmd window in Windows. Then run `pio run -t menuconfig` outside platformio. The menuconfig navigation seems to work ok by this methos. 
I close this issue now, it is meant to help others that might experience the same problem when following the platformio tutorial on ttn-esp32 wiki.
