### ISSUE TITLE
No TTN option in component config anymore

### ISSUE THREAD

**Issue by Kientopf** [manuelbl/ttn-esp32#56]
There is no option "The Things Network" in esp.idf menuconfig as it should be.
See the Get Started text: "In the menu, select Component config ---> and then select The Things Network ---> (at the very bottom)."

And this is the menu in Component config:
<img width="795" alt="component config no ttn" src="https://user-images.githubusercontent.com/11016223/188228808-798cb069-b99a-4919-b56d-00c28d413e3f.png">

**Comment by manuelbl** [comment]
In order to reproduce the problem, can you provide more information regarding your environment: ESP-IDF version, operating system etc.

**Comment by Kientopf** [comment]
Thank you very much for the quick reply. I just managed to solve the problem by myself, it was a stupid path problem (there was a space in the path).
