### ISSUE TITLE
Can I communicate peer to peer?

### ISSUE THREAD

**Issue by julioj4pa** [manuelbl/ttn-esp32#58]
Hello, awesome code. Thank you for sharing.
I'm already using Wifi of ESP-IDF to communication.
I'm so newbie, I read library but I can't find how to communicate peer to peer... Is it possible? If is how can I do it?
I'm really thankful for attention.

**Comment by manuelbl** [comment]
This library is specifically built for The Things Network, which does not support peer-to-peer communication. All communication is from the device via gateway to the network (uplink). And it‘s asymmetric. The downlink has an even lower bandwidth.

**Comment by matthias-bs** [comment]
For peer to peer communication, you might want to have a look at https://github.com/jgromes/RadioLib.
